export const POSTS = [
  {
    slug: "roas-vs-mer-which-metric-actually-matters",
    title: "ROAS vs MER: Which Metric Actually Matters for D2C Profitability?",
    excerpt:
      "Every D2C founder obsesses over ROAS. But blended ROAS is a vanity metric that hides your true marketing efficiency. Here's why MER (Marketing Efficiency Ratio) is the number you should track instead.",
    category: "Ads & Growth",
    tag_color: "#ddb7ff",
    read_time: "7 min read",
    date: "Jun 28, 2026",
    featured: true,
    icon: "ads_click",
    icon_color: "#ddb7ff",
    image: "/visuals/marketing-command-desk.png",
    image_alt: "Marketing analytics command desk with ad performance dashboards",
    author: "Saransh Gulati",
    author_role: "Founder, GrowthOS",
  },
  {
    slug: "how-to-reduce-rto-rate-d2c-india",
    title: "How to Cut Your RTO Rate Below 10%: The Definitive Guide for Indian D2C",
    excerpt:
      "Return-to-origin is the silent killer of D2C margins in India. With COD still at 60%+ of orders, a 25% RTO rate can wipe out your entire profit. Here's the exact playbook top brands use to get below 10%.",
    category: "Operations",
    tag_color: "#7bd0ff",
    read_time: "9 min read",
    date: "Jun 22, 2026",
    featured: true,
    icon: "local_shipping",
    icon_color: "#7bd0ff",
    image: "/visuals/inventory-warehouse.png",
    image_alt: "Ecommerce warehouse with shipping parcels and operations dashboard",
    author: "Priya Mehta",
    author_role: "Operations Lead, GrowthOS",
  },
  {
    slug: "shopify-profit-calculator-true-margin",
    title: "Your Shopify Revenue Is Lying to You: How to Calculate True Profit Per Order",
    excerpt:
      "Shopify shows you revenue. It doesn't show you what you actually keep. Factor in COGS, shipping, returns, payment gateway fees, ad attribution, and GST — and most brands discover they're making 40% less than they thought.",
    category: "Finance",
    tag_color: "#4ade80",
    read_time: "6 min read",
    date: "Jun 15, 2026",
    featured: false,
    icon: "account_balance",
    icon_color: "#4ade80",
    image: "/visuals/founder-workspace.png",
    image_alt: "Founder workspace with GrowthOS finance and profit dashboards",
    author: "Saransh Gulati",
    author_role: "Founder, GrowthOS",
  },
  {
    slug: "whatsapp-cart-recovery-playbook",
    title: "The WhatsApp Cart Recovery Playbook That Generated ₹2.4Cr for Apex Footwear",
    excerpt:
      "76% cart abandonment. Zero automation. That was Apex Footwear 6 months ago. Here's the exact 3-message WhatsApp sequence — with timing, copy, and discount strategy — that now recovers 28% of abandoned carts.",
    category: "WhatsApp & CRM",
    tag_color: "#4ade80",
    read_time: "8 min read",
    date: "Jun 10, 2026",
    featured: false,
    icon: "chat",
    icon_color: "#4ade80",
    image: "/visuals/marketing-command-desk.png",
    image_alt: "Customer messaging and marketing automation command desk",
    author: "Rohan Kapoor",
    author_role: "Growth Advisor",
  },
  {
    slug: "meta-ads-creative-fatigue-signals",
    title: "5 Signs Your Meta Ads Creative Is Fatigued (And What to Do About It)",
    excerpt:
      "CPM creeping up. CTR falling. ROAS declining week over week. Your creative isn't the problem — it's just tired. Learn how to read fatigue signals early and rotate creative before performance craters.",
    category: "Ads & Growth",
    tag_color: "#ddb7ff",
    read_time: "5 min read",
    date: "Jun 4, 2026",
    featured: false,
    icon: "ads_click",
    icon_color: "#ddb7ff",
    image: "/visuals/marketing-command-desk.png",
    image_alt: "Ad creative performance dashboard for D2C campaigns",
    author: "Ananya Singh",
    author_role: "Ads Specialist",
  },
  {
    slug: "rfm-segmentation-d2c-guide",
    title: "RFM Segmentation: The Framework Behind ₹50Cr Revenue for India's Top D2C Brands",
    excerpt:
      "Recency, Frequency, Monetary — three numbers that tell you everything about your customers. Learn how to build RFM segments, identify your VIPs, and design campaigns that 3x repeat purchase rates.",
    category: "Customer Analytics",
    tag_color: "#c0c1ff",
    read_time: "10 min read",
    date: "May 28, 2026",
    featured: false,
    icon: "people",
    icon_color: "#c0c1ff",
    image: "/visuals/founder-workspace.png",
    image_alt: "Customer analytics dashboard in a founder workspace",
    author: "Saransh Gulati",
    author_role: "Founder, GrowthOS",
  },
  {
    slug: "google-shopping-feed-optimisation",
    title: "Google Shopping Feed Optimisation: From 1.2% CTR to 3.8% in 30 Days",
    excerpt:
      "Most D2C brands treat their Google Shopping feed as an afterthought. But your feed title, image, and price architecture directly determine CPCs and ROAS. Here's the optimisation checklist that moved Urban Thread Co's CTR 3x.",
    category: "Ads & Growth",
    tag_color: "#ddb7ff",
    read_time: "7 min read",
    date: "May 21, 2026",
    featured: false,
    icon: "search",
    icon_color: "#ddb7ff",
    image: "/visuals/marketing-command-desk.png",
    image_alt: "Search and shopping campaign analytics dashboard",
    author: "Vikram Nair",
    author_role: "CMO, Urban Thread Co",
  },
  {
    slug: "d2c-inventory-forecast-prevent-stockouts",
    title: "How to Never Run Out of Stock Again: AI-Powered Inventory Forecasting for D2C",
    excerpt:
      "A stockout during a sale is a nightmare — lost revenue, angry customers, wasted ad spend. Learn how leading D2C brands use sell-through velocity, seasonality, and supplier lead times to forecast inventory with 94% accuracy.",
    category: "Operations",
    tag_color: "#7bd0ff",
    read_time: "8 min read",
    date: "May 14, 2026",
    featured: false,
    icon: "inventory_2",
    icon_color: "#7bd0ff",
    image: "/visuals/inventory-warehouse.png",
    image_alt: "Inventory forecasting dashboard inside an ecommerce warehouse",
    author: "Aisha Patel",
    author_role: "Founder, Pure Origins",
  },
  {
    slug: "ltv-cac-ratio-benchmarks-india-d2c",
    title: "LTV:CAC Benchmarks for Indian D2C — What's Healthy and What's a Red Flag",
    excerpt:
      "A 3:1 LTV:CAC ratio is the oft-cited benchmark. But in India, where cash-on-delivery dominates and returns are high, the math is different. Here are real benchmarks across categories — beauty, fashion, food, and home.",
    category: "Finance",
    tag_color: "#4ade80",
    read_time: "6 min read",
    date: "May 7, 2026",
    featured: false,
    icon: "trending_up",
    icon_color: "#4ade80",
    image: "/visuals/founder-workspace.png",
    image_alt: "Growth metrics and LTV CAC dashboard on a founder desk",
    author: "Saransh Gulati",
    author_role: "Founder, GrowthOS",
  },
  {
    slug: "founder-ai-vs-data-analyst-hire",
    title: "Should Your D2C Brand Hire a Data Analyst or Use AI? The Honest Answer",
    excerpt:
      "At ₹30L+ MRR, most founders hire a data analyst. But modern AI tools can replace 80% of what an analyst does — instantly. Here's when to hire a human and when to let AI handle the data work.",
    category: "AI & Automation",
    tag_color: "#fb923c",
    read_time: "5 min read",
    date: "Apr 30, 2026",
    featured: false,
    icon: "psychology",
    icon_color: "#fb923c",
    image: "/visuals/ai-operating-system.png",
    image_alt: "AI operating system interface with connected business insights",
    author: "Saransh Gulati",
    author_role: "Founder, GrowthOS",
  },
  {
    slug: "cod-to-prepaid-conversion-strategy",
    title: "COD to Prepaid: The Conversion Playbook That Boosted Net Margins by 8%",
    excerpt: "COD is a necessary evil in Indian D2C. But with the right incentives and messaging, you can shift 30-50% of COD orders to prepaid.",
    category: "Operations",
    read_time: "5 min read",
    date: "Jun 28, 2026",
    tag_color: "#fb923c",
    image: "/visuals/ai-operating-system.png",
    image_alt: "AI operating system interface with connected business insights",
    author: "Saransh Gulati",
    author_role: "Founder, GrowthOS",
  },
];
