import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      // ── Stitch Design System — GrowthOS / D2C OS ────────────────────────────
      fontFamily: {
        // Primary – UI body text
        inter: ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        // Secondary – labels, nav, code
        geist: ["Geist", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "label-sm": ["Geist", "sans-serif"],
        "code-sm": ["Geist", "monospace"],
        "tiny-tracking": ["Geist", "sans-serif"],
        // Legacy fallbacks
        syne: ["Inter", "sans-serif"],
        mono: ["Geist", "monospace"],
      },
      fontSize: {
        "body-md":        ["14px", { lineHeight: "1.5",  fontWeight: "400" }],
        "body-lg":        ["18px", { lineHeight: "1.6",  fontWeight: "400" }],
        "headline-md":    ["24px", { lineHeight: "1.3",  fontWeight: "600" }],
        "headline-lg":    ["32px", { lineHeight: "1.2",  letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md":       ["14px", { lineHeight: "1.4",  letterSpacing: "0.01em",  fontWeight: "500" }],
        "label-sm":       ["12px", { lineHeight: "1.2",  letterSpacing: "0.05em",  fontWeight: "600" }],
        "code-sm":        ["13px", { lineHeight: "1.6",  fontWeight: "400" }],
        "tiny-tracking":  ["10px", { lineHeight: "1",    letterSpacing: "0.1em",   fontWeight: "700" }],
      },
      colors: {
        // ── Stitch Palette ────────────────────────────────────────────────────
        background:                 "#0b1326",
        "on-background":            "#dbe2fd",
        surface:                    "#0b1326",
        "surface-dim":              "#0b1326",
        "surface-bright":           "#31394e",
        "surface-container-lowest": "#060e20",
        "surface-container-low":    "#131b2e",
        "surface-container":        "#171f33",
        "surface-container-high":   "#222a3e",
        "surface-container-highest":"#2d3449",
        "surface-variant":          "#2d3449",
        "surface-tint":             "#c0c1ff",
        "on-surface":               "#dbe2fd",
        "on-surface-variant":       "#c7c4d7",
        "inverse-surface":          "#dbe2fd",
        "inverse-on-surface":       "#283044",
        outline:                    "#918f9a",
        "outline-variant":          "#464554",
        primary:                    "#c0c1ff",
        "on-primary":               "#292b5e",
        "primary-container":        "#c0c1ff",
        "on-primary-container":     "#4b4d83",
        "primary-fixed":            "#e1e0ff",
        "primary-fixed-dim":        "#c0c1ff",
        "inverse-primary":          "#585990",
        secondary:                  "#ddb7ff",
        "on-secondary":             "#40215e",
        "secondary-container":      "#583876",
        "on-secondary-container":   "#cba6ed",
        tertiary:                   "#c3e7ff",
        "on-tertiary":              "#00344a",
        "tertiary-container":       "#7bd0ff",
        "on-tertiary-container":    "#005979",
        error:                      "#ffb4ab",
        "on-error":                 "#690005",
        "error-container":          "#93000a",
        // ── Accent Colors ─────────────────────────────────────────────────────
        "success-accent":           "#4ade80",
        "info-accent":              "#60a5fa",
        "warning-accent":           "#fb923c",
        "code-indigo":              "#8083ff",
        // ── Legacy alias (keep existing code working) ─────────────────────────
        growthos: {
          500: "#c0c1ff",
          accent: "#c0c1ff",
          bg0:    "#0b1326",
          bg1:    "#131b2e",
          border: "#464554",
          text:   "#dbe2fd",
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm:      "0.25rem",
        md:      "0.5rem",
        lg:      "0.75rem",
        xl:      "1rem",
        "2xl":   "1.5rem",
        full:    "9999px",
      },
      spacing: {
        "stack-xs":       "4px",
        "stack-sm":       "8px",
        "stack-md":       "16px",
        "stack-lg":       "24px",
        "stack-xl":       "48px",
        "gutter":         "24px",
        "margin-desktop": "40px",
        "sidebar-width":  "256px",
        "header-height":  "64px",
      },
      backdropBlur: {
        xs:  "4px",
        sm:  "8px",
        md:  "12px",
        lg:  "16px",
        xl:  "20px",
        "2xl": "40px",
      },
      boxShadow: {
        "glass":   "0 8px 32px rgba(0, 0, 0, 0.4), inset 0 1px 0 rgba(255,255,255,0.05)",
        "glow-primary": "0 0 20px rgba(192, 193, 255, 0.15)",
        "glow-success": "0 0 20px rgba(74, 222, 128, 0.15)",
      },
    },
  },
  plugins: [],
};

export default config;
