import {
  Activity,
  AlertTriangle,
  ArrowRight,
  BadgeCheck,
  BarChart3,
  Bell,
  Bot,
  Boxes,
  BrainCircuit,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  Circle,
  CircleDollarSign,
  CirclePlay,
  CircleSlash2,
  CircleX,
  ClipboardList,
  Clock3,
  ContactRound,
  Copy,
  CreditCard,
  Crown,
  Download,
  FileBarChart,
  FileSearch,
  FileText,
  Gauge,
  HelpCircle,
  Home,
  Image as ImageIcon,
  Inbox,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  LineChart,
  Link2,
  LockKeyhole,
  LogOut,
  Mail,
  Megaphone,
  MessageCircle,
  MonitorSmartphone,
  Package,
  PackageCheck,
  PackageSearch,
  Palette,
  PenLine,
  Phone,
  PieChart,
  RefreshCcw,
  Repeat2,
  Route,
  Search,
  SearchCheck,
  Send,
  Settings,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Star,
  Store,
  Tag,
  Timer,
  Truck,
  User,
  Users,
  Video,
  WandSparkles,
  Warehouse,
  Workflow,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { CSSProperties } from "react";

import { cn } from "@/lib/utils";

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  add_circle: CheckCircle2,
  ad_copy: Megaphone,
  ads: Megaphone,
  ads_click: Megaphone,
  alert: AlertTriangle,
  analytics: BarChart3,
  arrow_forward: ArrowRight,
  assignment_return: PackageCheck,
  attribution: Link2,
  audit: FileSearch,
  audit_logs: FileSearch,
  auto_awesome: Sparkles,
  auto_awesome_mosaic: WandSparkles,
  automation: Workflow,
  bar_chart: BarChart3,
  bar_chart_4_bars: BarChart3,
  billing: CreditCard,
  blog: FileText,
  bolt: Zap,
  bot: Bot,
  bubble_chart: PieChart,
  budget: SlidersHorizontal,
  calendar: Calendar,
  calendar_month: Calendar,
  campaign: Megaphone,
  caption: ImageIcon,
  category: Boxes,
  chat: MessageCircle,
  check: Check,
  check_circle: CheckCircle2,
  circle: Circle,
  close: X,
  contacts: ContactRound,
  content: PenLine,
  content_copy: Copy,
  copy: Copy,
  credit_card: CreditCard,
  crm: ContactRound,
  customers: Users,
  dashboard: LayoutDashboard,
  devices: MonitorSmartphone,
  download: Download,
  edit_note: PenLine,
  email: Mail,
  event_repeat: Repeat2,
  expand_more: ChevronDown,
  export: Download,
  finance: Landmark,
  forecast: LineChart,
  founder_ai: Sparkles,
  google: Search,
  grid_view: LayoutGrid,
  group: Users,
  help: HelpCircle,
  home: Home,
  hourglass_empty: Clock3,
  hub: Link2,
  image: ImageIcon,
  inbox: Inbox,
  insights: Sparkles,
  integrations: Link2,
  inventory: PackageSearch,
  inventory_2: PackageSearch,
  link: Link2,
  line_chart: LineChart,
  linechart: LineChart,
  local_offer: Tag,
  local_shipping: Truck,
  lock: LockKeyhole,
  logout: LogOut,
  mail: Mail,
  manage_search: FileSearch,
  marketing: Megaphone,
  menu: LayoutGrid,
  meta: Megaphone,
  money_off: CircleSlash2,
  new_releases: BadgeCheck,
  notifications: Bell,
  operations: Warehouse,
  package: Package,
  palette: Palette,
  payments: CircleDollarSign,
  pending_actions: ClipboardList,
  person: User,
  phone: Phone,
  pie_chart: PieChart,
  play_circle: CirclePlay,
  pricing: Tag,
  product_desc: Tag,
  products: PackageSearch,
  psychology: BrainCircuit,
  query_stats: LineChart,
  reports: FileBarChart,
  repeat: Repeat2,
  refreshccw: RefreshCcw,
  refresh_ccw: RefreshCcw,
  route: Route,
  savings: CircleDollarSign,
  schedule: Clock3,
  search: Search,
  security: ShieldCheck,
  shieldcheck: ShieldCheck,
  sell: Tag,
  send: Send,
  seo: SearchCheck,
  settings: Settings,
  share: Link2,
  shopify: ShoppingBag,
  smart_toy: Bot,
  space_dashboard: LayoutDashboard,
  star: Star,
  store: Store,
  summarize: FileText,
  timer: Timer,
  touch_app: Activity,
  travel_explore: SearchCheck,
  trending_down: LineChart,
  trending_up: LineChart,
  tune: SlidersHorizontal,
  ugc_hook: Video,
  video_script: Video,
  videocam: Video,
  vip: Crown,
  whatsapp: MessageCircle,
  white_label: Palette,
  workspace_premium: Crown,
};

interface AppIconProps {
  name?: string;
  className?: string;
  size?: number;
  strokeWidth?: number;
  ariaLabel?: string;
  style?: CSSProperties;
}

export function AppIcon({
  name = "circle",
  className,
  size = 20,
  strokeWidth = 1.9,
  ariaLabel,
  style,
}: AppIconProps) {
  const key = name.replace(/-/g, "_");
  const Icon = ICONS[key] || ICONS[name] || Circle;

  return (
    <Icon
      aria-hidden={ariaLabel ? undefined : true}
      aria-label={ariaLabel}
      className={cn("shrink-0", className)}
      size={size}
      strokeWidth={strokeWidth}
      style={style}
    />
  );
}
