import {
  Activity,
  AlertTriangle,
  ArrowRight,
  BadgeCheck,
  BarChart3,
  Bell,
  Bot,
  BookOpen,
  Boxes,
  BrainCircuit,
  Calendar,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  Circle,
  CircleDollarSign,
  CirclePlay,
  CircleSlash2,
  CircleX,
  ClipboardList,
  Clock3,
  ContactRound,
  Copy,
  CreditCard,
  Crown,
  Download,
  Eye,
  EyeOff,
  FileBarChart,
  FileSearch,
  FileText,
  FlaskConical,
  Flower2,
  Footprints,
  Gauge,
  HelpCircle,
  Home,
  Image as ImageIcon,
  Inbox,
  IndianRupee,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Lightbulb,
  LineChart,
  Link2,
  LockKeyhole,
  LockOpen,
  LogOut,
  Mail,
  MailCheck,
  Megaphone,
  MessageCircle,
  MonitorSmartphone,
  Package,
  PackageCheck,
  PackageSearch,
  Palette,
  PenLine,
  Phone,
  PieChart,
  Plus,
  RefreshCcw,
  RefreshCw,
  Repeat2,
  Route,
  Search,
  SearchCheck,
  SearchX,
  Send,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Shirt,
  SlidersHorizontal,
  Sparkles,
  Sprout,
  Star,
  Store,
  Tag,
  Timer,
  Truck,
  User,
  Users,
  Video,
  WandSparkles,
  Warehouse,
  Wine,
  Workflow,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { CSSProperties } from "react";

import { cn } from "@/lib/utils";

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  account_balance: Landmark,
  account_balance_wallet: CircleDollarSign,
  account_tree: Workflow,
  add_circle: CheckCircle2,
  ad_copy: Megaphone,
  ads: Megaphone,
  ads_click: Megaphone,
  alert: AlertTriangle,
  analytics: BarChart3,
  arrow_forward: ArrowRight,
  assignment_return: PackageCheck,
  attribution: Link2,
  audit: FileSearch,
  audit_logs: FileSearch,
  auto_awesome: Sparkles,
  auto_awesome_mosaic: WandSparkles,
  automation: Workflow,
  bar_chart: BarChart3,
  bar_chart_4_bars: BarChart3,
  billing: CreditCard,
  blog: FileText,
  bolt: Zap,
  book_open: BookOpen,
  bot: Bot,
  bubble_chart: PieChart,
  budget: SlidersHorizontal,
  calendar: Calendar,
  calendar_month: Calendar,
  campaign: Megaphone,
  caption: ImageIcon,
  category: Boxes,
  chat: MessageCircle,
  check: Check,
  check_circle: CheckCircle2,
  circle: Circle,
  close: X,
  contacts: ContactRound,
  content: PenLine,
  content_copy: Copy,
  copy: Copy,
  credit_card: CreditCard,
  crm: ContactRound,
  customers: Users,
  dashboard: LayoutDashboard,
  devices: MonitorSmartphone,
  download: Download,
  edit_note: PenLine,
  eco: Leaf,
  email: Mail,
  error: AlertTriangle,
  event_repeat: Repeat2,
  expand_more: ChevronDown,
  export: Download,
  eye: Eye,
  eye_off: EyeOff,
  finance: Landmark,
  forecast: LineChart,
  founder_ai: Sparkles,
  google: Search,
  grid_view: LayoutGrid,
  group: Users,
  help: HelpCircle,
  home: Home,
  hourglass_empty: Clock3,
  hub: Link2,
  image: ImageIcon,
  inbox: Inbox,
  insights: Sparkles,
  integrations: Link2,
  indian_rupee: IndianRupee,
  inventory: PackageSearch,
  inventory_2: PackageSearch,
  key: KeyRound,
  link: Link2,
  lightbulb: Lightbulb,
  line_chart: LineChart,
  linechart: LineChart,
  local_bar: Wine,
  local_florist: Flower2,
  local_mall: ShoppingBag,
  local_offer: Tag,
  local_shipping: Truck,
  lock: LockKeyhole,
  lock_open: LockOpen,
  lock_reset: RefreshCcw,
  logout: LogOut,
  mail: Mail,
  mark_email_read: MailCheck,
  manage_search: FileSearch,
  marketing: Megaphone,
  menu: LayoutGrid,
  menu_book: BookOpen,
  meta: Megaphone,
  money_off: CircleSlash2,
  new_releases: BadgeCheck,
  notifications: Bell,
  notifications_active: Bell,
  operations: Warehouse,
  package: Package,
  palette: Palette,
  payments: CircleDollarSign,
  pending_actions: ClipboardList,
  person: User,
  people: Users,
  payment: CreditCard,
  phone: Phone,
  pie_chart: PieChart,
  play_circle: CirclePlay,
  pricing: Tag,
  product_desc: Tag,
  products: PackageSearch,
  psychology: BrainCircuit,
  query_stats: LineChart,
  receipt_long: FileText,
  reports: FileBarChart,
  repeat: Repeat2,
  refreshccw: RefreshCcw,
  refresh_ccw: RefreshCcw,
  route: Route,
  savings: CircleDollarSign,
  schedule: Clock3,
  search: Search,
  search_insights: SearchCheck,
  search_off: SearchX,
  security: ShieldCheck,
  shieldcheck: ShieldCheck,
  sell: Tag,
  send: Send,
  seo: SearchCheck,
  settings: Settings,
  share: Link2,
  checkroom: Shirt,
  package_2: Package,
  shopify: ShoppingBag,
  smart_toy: Bot,
  space_dashboard: LayoutDashboard,
  spa: Sprout,
  star: Star,
  steps: Footprints,
  store: Store,
  summarize: FileText,
  timer: Timer,
  touch_app: Activity,
  travel_explore: SearchCheck,
  trending_down: LineChart,
  trending_up: LineChart,
  tune: SlidersHorizontal,
  ugc_hook: Video,
  verified: BadgeCheck,
  video_script: Video,
  videocam: Video,
  visibility: Eye,
  visibility_off: EyeOff,
  warehouse: Warehouse,
  whatsapp: MessageCircle,
  wine: Wine,
  workflow: Workflow,
  workspace: LayoutGrid,
  workspace_premium: Crown,
  zap: Zap,

  // Additional aliases
  add: Plus,
  add_circle_outline: Plus,
  photo_camera: Camera,
  refresh: RefreshCw,
  science: FlaskConical,
  sparkles: Sparkles,
  speed: Gauge,
  gauge: Gauge,
  flask: FlaskConical,
  camera: Camera,
  plus: Plus,
};

interface AppIconProps {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
  style?: CSSProperties;
}

export function AppIcon({ name, size = 20, className, strokeWidth = 2, style }: AppIconProps) {
  const Icon = ICONS[name] ?? HelpCircle;
  return (
    <Icon
      size={size}
      strokeWidth={strokeWidth}
      className={cn("shrink-0", className)}
      style={style}
    />
  );
}
